; PlatformIO Project Configuration File
; Re-Tech Fusion Hackathon — ESP32 IoT Node

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    bblanchon/ArduinoJson @ ^6.21.5
    knolleary/PubSubClient @ ^2.8

build_flags =
    -D CORE_DEBUG_LEVEL=0
