#pragma once

#include <Arduino.h>

// ─────────────────────────────────────────────────────────────────────────────
// Re-Tech Fusion — Part 3A edge ML / anomaly detection
//
// Two compile-time backends share an identical public API:
//
//   Primary  (default):  TFLite via EloquentTinyML
//     Needs:  include/model_data.h generated by tools/train_model.py
//             platformio.ini lib_dep:  eloquentarduino/EloquentTinyML
//
//   Fallback (define EDGE_FALLBACK_ZSCORE in build_flags):
//     Needs:  nothing — pure C++, no model file, works from cold boot
//     Note:   anomaly detection only; predictions are rolling means
// ─────────────────────────────────────────────────────────────────────────────

#define EDGE_CHANNELS          5
#define EDGE_WINDOW            5
#define EDGE_INPUT_SIZE        (EDGE_CHANNELS * EDGE_WINDOW)   // 25
#define EDGE_OUTPUT_SIZE       EDGE_CHANNELS                   // 5
#define EDGE_TENSOR_ARENA_SIZE (16 * 1024)                     // 16 KB

// Max normalised prediction error on any channel to declare an anomaly.
// Range 0–1 after min-max normalisation. 0.15 ≈ 15% of full-scale deviation.
#ifndef EDGE_ANOMALY_THRESHOLD
#define EDGE_ANOMALY_THRESHOLD 0.15f
#endif

struct EdgeResult {
    bool          valid;            // false until the first full window is ready
    bool          anomaly_detected;
    float         max_error;        // normalised (0–1); highest across all channels
    int           worst_channel;    // 0–4 index of channel with highest error
    unsigned long latency_ms;       // wall-clock milliseconds for inference
};

namespace EdgeInference {

// Call once in setup() after sensor drivers are initialised.
// Loads TFLite model (primary path) or resets z-score accumulators (fallback).
void begin();

// Push the latest 5-channel reading into the sliding-window buffer.
// NaN values are replaced with the corresponding channel default.
// Call every 1 s (in readAndPrintSensors, after applyFaultInjection).
//
// Channel order — MUST match train_model.py:
//   [0] ds18b20 temperature  (°C)
//   [1] bme/bmp temperature  (°C)
//   [2] bme humidity         (%) — pass 50.0f if BMP280
//   [3] bme/bmp pressure     (hPa)
//   [4] acs712 current       (A)
void push(const float readings[EDGE_CHANNELS]);

// Run inference on the last EDGE_WINDOW readings.
// Returns valid==false until EDGE_WINDOW readings have been pushed.
// Call every 10 s (in buildAndQueuePayload, after the [JSON] log line).
EdgeResult run();

// Returns true once EDGE_WINDOW readings have been collected.
bool isReady();

} // namespace EdgeInference
