#include "edge_inference.h"
#include <math.h>

// ─────────────────────────────────────────────────────────────────────────────
// Compile-time backend selection:
//   Default  → TFLite via EloquentTinyML (needs model_data.h + library)
//   Fallback → statistical z-score (define EDGE_FALLBACK_ZSCORE in build_flags)
// ─────────────────────────────────────────────────────────────────────────────

// ═══════════════════════════════════════════════════════════════════════════
// FALLBACK: z-score anomaly detection (no model file, no extra library)
// ═══════════════════════════════════════════════════════════════════════════
#ifdef EDGE_FALLBACK_ZSCORE

// Per-channel defaults used when the sensor is offline
static const float CH_DEFAULTS[EDGE_CHANNELS] = {25.0f, 25.0f, 50.0f, 1013.0f, 0.0f};
static const float ZSCORE_THRESHOLD = 2.0f;  // flag if |x-mean| > 2σ

namespace {

// Welford online variance accumulators
double g_mean[EDGE_CHANNELS]     = {};
double g_M2[EDGE_CHANNELS]       = {};
long   g_n                       = 0;

// Sliding window for context (same API as TFLite path)
float  g_window[EDGE_WINDOW][EDGE_CHANNELS];
int    g_head  = 0;
int    g_count = 0;

inline float safe(float v, int ch) {
    return (isnan(v) || isinf(v)) ? CH_DEFAULTS[ch] : v;
}

} // namespace

namespace EdgeInference {

void begin() {
    g_n = 0;
    g_head = g_count = 0;
    memset(g_mean, 0, sizeof(g_mean));
    memset(g_M2,   0, sizeof(g_M2));
    Serial.println(F("[INFO] EdgeML z-score fallback ready (no model file)"));
}

void push(const float readings[EDGE_CHANNELS]) {
    g_n++;
    for (int c = 0; c < EDGE_CHANNELS; c++) {
        float v = safe(readings[c], c);
        double delta = v - g_mean[c];
        g_mean[c] += delta / g_n;
        g_M2[c]   += delta * (v - g_mean[c]);
        g_window[g_head][c] = v;
    }
    g_head  = (g_head + 1) % EDGE_WINDOW;
    if (g_count < EDGE_WINDOW) g_count++;
}

bool isReady() { return g_count >= EDGE_WINDOW; }

EdgeResult run() {
    EdgeResult r{};
    r.valid = isReady();
    if (!r.valid || g_n < 10) return r;   // need ≥10 samples for stable stats

    const unsigned long t0 = millis();

    // Use the most recent reading (g_head points to next write slot, so last is g_head-1)
    int last = (g_head - 1 + EDGE_WINDOW) % EDGE_WINDOW;

    float max_z = 0.0f;
    int worst   = 0;
    for (int c = 0; c < EDGE_CHANNELS; c++) {
        if (g_n < 2) continue;
        double variance = g_M2[c] / (g_n - 1);
        double stddev   = (variance > 1e-8) ? sqrt(variance) : 1e-4;
        float z = fabsf((g_window[last][c] - (float)g_mean[c]) / (float)stddev);
        if (z > max_z) { max_z = z; worst = c; }
    }

    r.anomaly_detected = (max_z > ZSCORE_THRESHOLD);
    // Normalise z-score to roughly 0–1 for a consistent API (z=2 → 0.15 ≈ threshold)
    r.max_error     = max_z * (EDGE_ANOMALY_THRESHOLD / ZSCORE_THRESHOLD);
    r.worst_channel = worst;
    r.latency_ms    = millis() - t0;
    return r;
}

} // namespace EdgeInference

// ═══════════════════════════════════════════════════════════════════════════
// PRIMARY: TFLite via EloquentTinyML
// ═══════════════════════════════════════════════════════════════════════════
#else

#include <EloquentTinyML.h>
#include <eloquent_tinyml/tensorflow.h>
#include "model_data.h"   // generated by tools/train_model.py

// Per-channel defaults (must match train_model.py CHANNEL_DEFAULTS)
static const float CH_DEFAULTS[EDGE_CHANNELS] = {25.0f, 25.0f, 50.0f, 1013.0f, 0.0f};

namespace {

Eloquent::TinyML::TfLite<EDGE_INPUT_SIZE, EDGE_OUTPUT_SIZE, EDGE_TENSOR_ARENA_SIZE> g_ml;

float g_window[EDGE_WINDOW][EDGE_CHANNELS];
int   g_head  = 0;
int   g_count = 0;

// Normalise a single channel value into [0,1] using the constants from model_data.h
inline float normalise(float v, int ch) {
    float lo = EDGE_CHANNEL_MIN[ch];
    float hi = EDGE_CHANNEL_MAX[ch];
    float rng = hi - lo;
    if (rng < 1e-6f) rng = 1.0f;
    float n = (v - lo) / rng;
    if (n < 0.0f) n = 0.0f;
    if (n > 1.0f) n = 1.0f;
    return n;
}

inline float safeVal(float v, int ch) {
    return (isnan(v) || isinf(v)) ? CH_DEFAULTS[ch] : v;
}

} // namespace

namespace EdgeInference {

void begin() {
    g_head = g_count = 0;
    if (!g_ml.begin(MODEL_DATA)) {
        Serial.println(F("[ERROR] EdgeML: TFLite model failed to load!"));
    } else {
        Serial.printf("[INFO]  EdgeML TFLite ready — model %u B, arena %u B\n",
                      MODEL_DATA_LEN, (unsigned)EDGE_TENSOR_ARENA_SIZE);
    }
}

bool isReady() { return g_count >= EDGE_WINDOW; }

void push(const float readings[EDGE_CHANNELS]) {
    for (int c = 0; c < EDGE_CHANNELS; c++) {
        g_window[g_head][c] = safeVal(readings[c], c);
    }
    g_head  = (g_head + 1) % EDGE_WINDOW;
    if (g_count < EDGE_WINDOW) g_count++;
}

EdgeResult run() {
    EdgeResult r{};
    r.valid = isReady();
    if (!r.valid) return r;

    const unsigned long t0 = millis();

    // Flatten the ring buffer (oldest first) into the input tensor
    float input[EDGE_INPUT_SIZE];
    for (int w = 0; w < EDGE_WINDOW; w++) {
        int src = (g_head - EDGE_WINDOW + w + EDGE_WINDOW) % EDGE_WINDOW;
        for (int c = 0; c < EDGE_CHANNELS; c++) {
            input[w * EDGE_CHANNELS + c] = normalise(g_window[src][c], c);
        }
    }

    float output[EDGE_OUTPUT_SIZE] = {};
    g_ml.predict(input, output);

    // Compare prediction for the *latest* reading against normalised ground truth
    int latest = (g_head - 1 + EDGE_WINDOW) % EDGE_WINDOW;
    float max_err = 0.0f;
    int   worst   = 0;
    for (int c = 0; c < EDGE_CHANNELS; c++) {
        float actual = normalise(g_window[latest][c], c);
        float err    = fabsf(output[c] - actual);
        if (err > max_err) { max_err = err; worst = c; }
    }

    r.anomaly_detected = (max_err > EDGE_ANOMALY_THRESHOLD);
    r.max_error        = max_err;
    r.worst_channel    = worst;
    r.latency_ms       = millis() - t0;
    return r;
}

} // namespace EdgeInference

#endif // EDGE_FALLBACK_ZSCORE
